# Jenkins Master
jenkins:
  image: blacklabelops/jenkins
  container_name: jenkins
  ports:
   - "80:8080"
   - "50000:50000"
  volumes_from:
    - volumes
  env_file:
    - conf/jenkins-master.env
  labels:
    co.aulin.description: "Jenkins Continuous Integration System"
    co.aulin.service: "jenkins-master"
# Global volume container
volumes:
  image: blacklabelops/centos
  container_name: jenkins_data
  volumes:
    # Logging volumes
    - /var/log
    # Jenkins volume
    - /jenkins
  command: chown -R 1000:1000 /var/log /jenkins
# Nginx front end
#nginx:
#  container_name: nginx
#  build: ./nginx/
#  ports:
#    - "80:80"
#  links:
#    - jenkins
# Jenkins Slave
#slave:
#  image: blacklabelops/swarm-jdk8
#  links:
#    - jenkins:jenkins
#  env_file:
#    - jenkins-slave-.env
#  labels:
#    com.blacklabelops.description: "Jenkins Swarm JDK-8 Slave"
#    com.blacklabelops.service: "slave"
#    com.blacklabelops.applications: "java maven gradle"
