version: '2'
services:
  jenkins:
    image: blacklabelops/jenkins
    container_name: jenkins
    volumes_from:
      - volumes
    env_file:
      - conf/jenkins-master.env
  nginx:
    container_name: nginx
    build: ./nginx/
    ports:
      - "80:80"
  volumes:
    image: blacklabelops/centos
    container_name: jenkins_data
    volumes:
      # Logging volumes
      - /var/log
      # Jenkins volume
      - /jenkins
    command: chown -R 1000:1000 /var/log /jenkins
